# The default message wave-file. If the user chooses to delete the current message a
# default should exist. If the file wav-file specified here for the default doesn't
# exist or if the configuration file doesn't exist a default file should be created
# on start of the application. Generating a default file dynamically is only required
# for grade 5. The message in the default file should be hard coded in the application.

default_message = default.wav
         
# Current message (message_wav and message_text)

# The current message is the message that was set by the web configuration interface
# and should be saved when the application exits. If the current message is deleted the default
# should be played.

message_wav = currentmessage.wav

message_text = Welcome to the SIP Speaker. This is my own answering machine.

# Bellow is the interface that the sip server part should bind and listen to. To listen to all
# existing interfaces use the interface 0.0.0.0. (This is true for the web server as well.) 

sip_interface = 192.168.2.11

sip_port = 5060

# HTTP web server

http_interface = 192.168.2.11

http_port = 8080
